name: fhtd_full
channels:
  - conda-forge
  - defaults
  - potassco
dependencies:
  #mandatory: graph library
  - networkx>=2.2
  #TODO(jf): do we need this one?
  - numpy>=1.17.2
  #TODO(jf): do we need this one?
  - lxml>=4.1.1
  #mandatory: signal handling and kill pstrees
  - psutil
  #optional: largest clique via asp
  - clingo
  # TODO: pymonad pip
