name: fhtd_base
channels:
  - conda-forge
  - defaults
dependencies:
  #mandatory: graph library
  - networkx>=2.2
  #TODO(jf): do we need this one?
  - numpy>=1.17.2
  #TODO(jf): do we need this one?
  - lxml>=4.1.1
  #mandatory: signal handling and kill pstrees
  - psutil
