from fhtd.smt.smt_OptiMathSAT import FractionalHypertreeDecomposition_OptiMathSAT
# from fhtd.smt.smt_z3 import FractionalHypertreeDecomposition_z3
#from smt_pysmt import FractionalHypertreeDecomposition_pysmt
